# Generated by Django 5.1.4 on 2025-03-24 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('publication_year', models.IntegerField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='books/covers/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='books/pdfs/')),
                ('book_type', models.CharField(choices=[('history', 'تاريخي'), ('literature', 'أدبي'), ('science', 'علمي'), ('philosophy', 'فلسفة'), ('religion', 'ديني'), ('other', 'أخرى')], default='other', max_length=50)),
            ],
        ),
    ]
