# Generated by Django 5.1.4 on 2025-03-25 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_add_publication_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='download_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='source',
            field=models.CharField(max_length=100),
        ),
    ]
