# Generated by Django 5.1.4 on 2025-03-26 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_description_alter_book_download_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publish_year',
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, verbose_name='ISBN'),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(default='ar', max_length=20, verbose_name='Langue'),
        ),
        migrations.AddField(
            model_name='book',
            name='publish_date',
            field=models.CharField(blank=True, max_length=50, verbose_name='Année de publication'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=100, verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='book',
            name='download_link',
            field=models.URLField(blank=True, verbose_name='Lien de téléchargement'),
        ),
        migrations.AlterField(
            model_name='book',
            name='source',
            field=models.CharField(max_length=100, verbose_name='Source (API/Scraping)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titre'),
        ),
    ]
