# Generated by Django 5.1.4 on 2025-03-26 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_book_publish_year_book_isbn_book_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.URLField(blank=True, verbose_name='Image de couverture'),
        ),
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nombre de pages'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(default='fr', max_length=20, verbose_name='Langue'),
        ),
        migrations.AlterField(
            model_name='book',
            name='source',
            field=models.CharField(max_length=100, verbose_name='Source'),
        ),
    ]
