# Generated by Django 5.1.4 on 2025-03-07 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('title', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.FileField(upload_to='descriptions/')),
                ('video', models.FileField(upload_to='subtopic_videos/')),
                ('image', models.ImageField(upload_to='subtopic_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='title.maintopic')),
            ],
        ),
    ]
