# Generated by Django 5.1.4 on 2025-03-08 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subtitle', '0002_subtitle_remove_subtopic_main_topic'),
        ('title', '0002_maintitle_delete_maintopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitle',
            name='main_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='title.maintitle'),
        ),
        migrations.DeleteModel(
            name='SubTopic',
        ),
    ]
