# Generated by Django 5.1.4 on 2025-03-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subtitle', '0003_subtitle_main_title_delete_subtopic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtitle',
            name='image',
        ),
        migrations.AddField(
            model_name='subtitle',
            name='image_folder',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
