# Generated by Django 5.1.4 on 2025-03-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subtitle', '0005_remove_subtitle_image_folder_subtitle_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='subtitle',
            name='image',
        ),
        migrations.AddField(
            model_name='subtitle',
            name='images',
            field=models.ManyToManyField(blank=True, to='subtitle.image'),
        ),
    ]
