# Generated by Django 5.1.4 on 2025-03-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subtitle', '0002_subtitle_remove_subtopic_main_topic'),
        ('title', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.FileField(upload_to='descriptions/')),
                ('image', models.ImageField(upload_to='images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
            ],
        ),
        migrations.DeleteModel(
            name='MainTopic',
        ),
    ]
