# Generated by Django 5.1.4 on 2025-03-11 21:36

import title.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0002_maintitle_delete_maintopic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintitle',
            name='image',
            field=models.ImageField(upload_to=title.models.get_image_upload_path),
        ),
    ]
